# -*- coding: utf-8 -*-
"""Selectraifelse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWWfrVremLShRAmQI7Pvx6t06zgQzwHj
"""

import json

def infer_user_type(question):
    q = question.lower()
    if any(word in q for word in ["roi", "ratio", "earnings", "balance sheet", "cash flow", "asset", "liabilities"]):
        return "financial analyst"
    elif any(word in q for word in ["change", "increase", "decrease", "trend"]):
        return "business manager"
    elif any(word in q for word in ["explain", "what is", "how do", "define"]):
        return "novice user"
    elif any(word in q for word in ["calculate", "/", "*", "-", "+", "percentage change"]):
        return "technical expert"
    elif any(word in q for word in ["shareholder", "dividend", "investment", "stock"]):
        return "investor"
    else:
        return "general user"

# Load dataset
with open("tatqa_dataset_test_gold.json") as f:
    data = json.load(f)

# Extract user preference per question
user_preferences = []
for example in data:
    for q in example["questions"]:
        user_pref = infer_user_type(q["question"])
        user_preferences.append({
            "question": q["question"],
            "preference": user_pref
        })

for entry in user_preferences[:10]:
    print(f"Q: {entry['question']}\n → User Type: {entry['preference']}\n")